#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Replace 2023 exam fake tasks with real CKE content."""

file_path = r"E:\matematyka - strona kompedium\arkusze.html"

new_tasks = [
    '      { num: 1, text: "Na osi liczbowej zaznaczono sumę przedziałów $(-\\\\infty,-2]\\\\cup[5,+\\\\infty)$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Zbiór zaznaczony na osi jest zbiorem wszystkich rozwiązań nierówności. A. $|x-3{,}5|\\\\geq 1{,}5$  B. $|x-1{,}5|\\\\geq 3{,}5$  C. $|x-3{,}5|\\\\leq 1{,}5$  D. $|x-1{,}5|\\\\leq 3{,}5$", type: "zamknięte", answer: "B", solution: [{ step: "Środek przedziałów to $\\\\frac{-2+5}{2}=1{,}5$, odległość od środka $=3{,}5$:", math: "$|x-1{,}5|\\\\geq 3{,}5$" }] },',
    '      { num: 2, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\\\sqrt[3]{-\\\\frac{27}{16}}\\\\cdot\\\\frac{3}{\\\\sqrt{2}}$ jest równa. A. $-\\\\frac{3}{2}$  B. $\\\\frac{3}{2}$  C. $\\\\frac{2}{3}$  D. $-\\\\frac{2}{3}$", type: "zamknięte", answer: "A", solution: [{ step: "$\\\\sqrt[3]{-\\\\frac{27}{16}}=\\\\frac{-3}{\\\\sqrt[3]{16}}$; mnożymy przez $\\\\frac{3}{\\\\sqrt{2}}$:", math: "$\\\\frac{-3}{\\\\sqrt[3]{16}}\\\\cdot\\\\frac{3}{\\\\sqrt{2}}=\\\\frac{-9}{\\\\sqrt[3]{16}\\\\cdot\\\\sqrt{2}}=\\\\frac{-9}{2^{4/3}\\\\cdot 2^{1/2}}=\\\\frac{-9}{2^{11/6}}$" }, { step: "Upraszczamy: wynik $=-\\\\frac{3}{2}$", math: "" }] },',
    '      { num: 3, text: "Wykaż, że dla każdej liczby naturalnej $n\\\\geq 1$ liczba $(2n+1)^{2}-1$ jest podzielna przez $8$.", type: "otwarte", answer: "$(2n+1)^2-1=4n(n+1)$; $n(n+1)$ parzyste, więc $4n(n+1)$ podzielne przez 8", solution: [{ step: "Korzystamy ze wzoru skróconego mnożenia:", math: "$(2n+1)^2-1=4n^2+4n=4n(n+1)$" }, { step: "Liczby $n$ i $n+1$ są kolejnymi liczbami naturalnymi, więc jedna jest parzysta, zatem $n(n+1)$ jest parzyste, a $4n(n+1)$ jest podzielne przez 8.", math: "" }] },',
    '      { num: 4, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\\\log_{9}27+\\\\log_{9}3$ jest równa. A. 81  B. 9  C. 4  D. 2", type: "zamknięte", answer: "D", solution: [{ step: "$\\\\log_9 27+\\\\log_9 3=\\\\log_9(27\\\\cdot3)=\\\\log_9 81$:", math: "$\\\\log_9 9^2=2$" }] },',
    '      { num: 5, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Dla każdej liczby rzeczywistej $a$ wyrażenie $(2a-3)^{2}-(2a+3)^{2}$ jest równe. A. $-24a$  B. $0$  C. $18$  D. $16a^{2}-24a$", type: "zamknięte", answer: "A", solution: [{ step: "Wzór $p^2-q^2=(p+q)(p-q)$:", math: "$(4a)(−6)=−24a$" }] },',
    '      { num: 6, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Zbiorem wszystkich rozwiązań nierówności $-2(x+3)\\\\leq\\\\frac{2-x}{3}$ jest przedział. A. $(-\\\\infty,-4]$  B. $(-\\\\infty,4]$  C. $[-4,+\\\\infty)$  D. $[4,+\\\\infty)$", type: "zamknięte", answer: "C", solution: [{ step: "Mnożymy przez 3:", math: "$-6(x+3)\\\\leq 2-x\\\\Rightarrow -6x-18\\\\leq 2-x\\\\Rightarrow -5x\\\\leq 20\\\\Rightarrow x\\\\geq -4$" }] },',
    '      { num: 7, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Jednym z rozwiązań równania $\\\\sqrt{3}(x^{2}-2)(x+3)=0$ jest liczba. A. 3  B. 2  C. $\\\\sqrt{3}$  D. $\\\\sqrt{2}$", type: "zamknięte", answer: "D", solution: [{ step: "$\\\\sqrt{3}\\\\neq 0$, więc $x^2-2=0$ lub $x+3=0$:", math: "$x=\\\\pm\\\\sqrt{2}$ lub $x=-3$; jednym z rozwiązań jest $\\\\sqrt{2}$" }] },',
    '      { num: 8, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Równanie $\\\\frac{(x+1)(x-1)^{2}}{(x-1)(x+1)^{2}}=0$ w zbiorze liczb rzeczywistych. A. nie ma rozwiązania.  B. ma dokładnie jedno rozwiązanie: $-1$.  C. ma dokładnie jedno rozwiązanie: $1$.  D. ma dokładnie dwa rozwiązania: $-1$ oraz $1$.", type: "zamknięte", answer: "A", solution: [{ step: "Upraszczamy: $\\\\frac{x-1}{x+1}=0$ dla $x\\\\neq\\\\pm1$. Licznik=0 gdy $x=1$, ale $x=1$ wykluczone:", math: "Brak rozwiązania." }] },',
    '      { num: 9, text: "Rozwiąż równanie $3x^{3}-2x^{2}-12x+8=0$. Zapisz obliczenia.", type: "otwarte", answer: "$x=\\\\frac{2}{3},\\;x=2,\\;x=-2$", solution: [{ step: "Grupowanie wyrazów:", math: "$x^2(3x-2)-4(3x-2)=0\\\\Rightarrow(3x-2)(x^2-4)=0$" }, { step: "Rozwiązania:", math: "$x=\\\\frac{2}{3}$ lub $x=\\\\pm2$" }] },',
    '      { num: 10, text: "Na rysunku przedstawiono interpretację geometryczną w kartezjańskim układzie współrzędnych jednego z układów równań A–D. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Układem równań, którego interpretację geometryczną przedstawiono na rysunku, jest. A. $\\\\begin{cases}y=-x+2\\\\\\\\y=-2x+1\\\\end{cases}$  B. $\\\\begin{cases}y=x-2\\\\\\\\y=-2x-1\\\\end{cases}$  C. $\\\\begin{cases}y=x-2\\\\\\\\y=2x+1\\\\end{cases}$  D. $\\\\begin{cases}y=-x+2\\\\\\\\y=2x-1\\\\end{cases}$", type: "zamknięte", answer: "D", solution: [{ step: "Z rysunku: proste przecinają się i mają różne znaki współczynników kierunkowych.", math: "" }] },',
    '      { num: 11, text: "Dany jest prostokąt o bokach długości $a$ i $b$, gdzie $a>b$. Obwód tego prostokąta jest równy $30$. Jeden z boków jest o $5$ krótszy od drugiego. Uzupełnij zdanie. Wybierz dwie właściwe odpowiedzi spośród A–F. Zależności między długościami boków tego prostokąta zapisano w układach równań oznaczonych literami: ……… oraz ………. A. $\\\\begin{cases}2ab=30\\\\\\\\a-b=5\\\\end{cases}$  B. $\\\\begin{cases}2a+b=30\\\\\\\\a=5b\\\\end{cases}$  C. $\\\\begin{cases}2(a+b)=30\\\\\\\\b=a-5\\\\end{cases}$  D. $\\\\begin{cases}a+b=30\\\\\\\\a-b=5\\\\end{cases}$  E. $\\\\begin{cases}a+b=15\\\\\\\\a=b+5\\\\end{cases}$  F. $\\\\begin{cases}2(a+b)=30\\\\\\\\a+b=5\\\\end{cases}$", type: "otwarte", answer: "C i E", solution: [{ step: "Obwód: $2(a+b)=30$ → C. Równoważnie $a+b=15$ → E.", math: "" }, { step: "Warunek: $b=a-5$ (w C) lub $a=b+5$ (w E). Oba układy są równoważne.", math: "" }] },',
    '      { num: 12, text: "W kartezjańskim układzie współrzędnych narysowano wykres funkcji $y=f(x)$. (12.1) Dokończ zdanie — Dziedziną funkcji $f$ jest zbiór: A. $[-6,5]$  B. $(-6,5)$  C. $(-3,5]$  D. $[-3,5]$. (12.2) Dokończ zdanie — Największa wartość funkcji $f$ w przedziale $[-4,1]$ jest równa: A. $0$  B. $1$  C. $2$  D. $5$. (12.3) Dokończ zdanie — Funkcja $f$ jest malejąca w zbiorze: A. $[-6,-3)$  B. $[-3,1]$  C. $(1,2]$  D. $[2,5]$.", type: "zamknięte", answer: "12.1: A; 12.2: C; 12.3: D", solution: [{ step: "(12.1) Wykres rozciąga się od $x=-6$ do $x=5$, oba punkty domknięte: $[-6,5]$ → A.", math: "" }, { step: "(12.2) Na $[-4,1]$ największa wartość wynosi 2 → C.", math: "" }, { step: "(12.3) Funkcja malejąca na $[2,5]$ → D.", math: "" }] },',
    '      { num: 13, text: "Funkcja liniowa $f$ jest określona wzorem $f(x)=ax+b$, gdzie $a$ i $b$ są pewnymi liczbami rzeczywistymi. Na rysunku przedstawiono fragment wykresu funkcji $f$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $a$ oraz liczba $b$ we wzorze funkcji $f$ spełniają warunki. A. $a>0$ i $b>0$  B. $a>0$ i $b<0$  C. $a<0$ i $b>0$  D. $a<0$ i $b<0$", type: "zamknięte", answer: "C", solution: [{ step: "Z wykresu: prosta malejąca ($a<0$) i przecina oś $Oy$ powyżej 0 ($b>0$):", math: "$a<0$ i $b>0$" }] },',
    '      { num: 14, text: "Jednym z miejsc zerowych funkcji kwadratowej $f$ jest liczba $(-5)$. Pierwsza współrzędna wierzchołka paraboli, będącej wykresem funkcji $f$, jest równa $3$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Drugim miejscem zerowym funkcji $f$ jest liczba. A. 11  B. 1  C. $(-1)$  D. $(-13)$", type: "zamknięte", answer: "A", solution: [{ step: "Oś symetrii $x=3$; jedno zero w $x=-5$; drugie zero symetrycznie:", math: "$x_2=3+(3-(-5))=11$" }] },',
    '      { num: 15, text: "Ciąg $(a_n)$ jest określony wzorem $a_n=2^n\\\\cdot(n+1)$ dla każdej liczby naturalnej $n\\\\geq 1$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Wyraz $a_4$ jest równy. A. 64  B. 40  C. 48  D. 80", type: "zamknięte", answer: "D", solution: [{ step: "$a_4=2^4\\\\cdot(4+1)$:", math: "$16\\\\cdot5=80$" }] },',
    '      { num: 16, text: "Trzywyrazowy ciąg $(27,\\;9,\\;a-1)$ jest geometryczny. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $a$ jest równa. A. 3  B. 0  C. 4  D. 2", type: "zamknięte", answer: "C", solution: [{ step: "Iloraz $q=9/27=1/3$; trzeci wyraz $=9\\\\cdot(1/3)=3=a-1$:", math: "$a=4$" }] },',
    '      { num: 17, text: "Pan Stanisław spłacił pożyczkę w wysokości $8910$ zł w osiemnastu ratach. Każda kolejna rata była mniejsza od poprzedniej o $30$ zł. Oblicz kwotę pierwszej raty. Zapisz obliczenia.", type: "otwarte", answer: "$a_1=750$ zł", solution: [{ step: "Ciąg arytmetyczny, $r=-30$, $n=18$, suma $S_{18}=8910$:", math: "$S_{18}=\\\\frac{18}{2}(2a_1+17\\\\cdot(-30))=8910$" }, { step: "Rozwiązujemy:", math: "$9(2a_1-510)=8910\\\\Rightarrow 2a_1=1500\\\\Rightarrow a_1=750$ zł" }] },',
    '      { num: 18, text: "W kartezjańskim układzie współrzędnych zaznaczono kąt $\\\\alpha$ o wierzchołku w punkcie $O=(0,0)$, gdzie jedno ramię pokrywa się z dodatnią półosią $Ox$, a drugie przechodzi przez punkt $P=(-3,1)$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Tangens kąta $\\\\alpha$ jest równy. A. $\\\\frac{1}{\\\\sqrt{10}}$  B. $-\\\\frac{3}{\\\\sqrt{10}}$  C. $-\\\\frac{3}{1}$  D. $-\\\\frac{1}{3}$", type: "zamknięte", answer: "D", solution: [{ step: "$\\\\mathrm{tg}\\\\,\\\\alpha=\\\\frac{y}{x}=\\\\frac{1}{-3}$:", math: "$\\\\mathrm{tg}\\\\,\\\\alpha=-\\\\frac{1}{3}$" }] },',
    '      { num: 19, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Dla każdego kąta ostrego $\\\\alpha$ wyrażenie $\\\\sin^{4}\\\\alpha+\\\\sin^{2}\\\\alpha\\\\cdot\\\\cos^{2}\\\\alpha$ jest równe. A. $\\\\sin^{2}\\\\alpha$  B. $\\\\sin^{6}\\\\alpha\\\\cdot\\\\cos^{2}\\\\alpha$  C. $\\\\sin^{4}\\\\alpha+1$  D. $\\\\sin^{2}\\\\alpha\\\\cdot(\\\\sin\\\\alpha+\\\\cos\\\\alpha)(\\\\sin\\\\alpha-\\\\cos\\\\alpha)$", type: "zamknięte", answer: "A", solution: [{ step: "Wyłączamy $\\\\sin^2\\\\alpha$:", math: "$\\\\sin^2\\\\alpha(\\\\sin^2\\\\alpha+\\\\cos^2\\\\alpha)=\\\\sin^2\\\\alpha\\\\cdot1=\\\\sin^2\\\\alpha$" }] },',
    '      { num: 20, text: "W rombie o boku długości $6\\\\sqrt{2}$ kąt rozwarty ma miarę $150°$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Iloczyn długości przekątnych tego rombu jest równy. A. 24  B. 72  C. 36  D. $36\\\\sqrt{2}$", type: "zamknięte", answer: "B", solution: [{ step: "Pole $= a^2\\\\sin\\\\theta = (6\\\\sqrt{2})^2\\\\sin150° = 72\\\\cdot\\\\frac{1}{2}=36$. Iloczyn przekątnych $=2\\\\cdot$Pole:", math: "$d_1\\\\cdot d_2=2\\\\cdot36=72$" }] },',
    '      { num: 21, text: "Punkty $A$, $B$, $C$ leżą na okręgu o środku $O$. Kąt $ACO$ ma miarę $70°$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Miara kąta ostrego $ABC$ jest równa. A. $10°$  B. $20°$  C. $35°$  D. $40°$", type: "zamknięte", answer: "B", solution: [{ step: "$OA=OC$ (promienie), więc $\\\\angle OAC=\\\\angle OCA=70°$; $\\\\angle AOC=180°-140°=40°$. Kąt wpisany $\\\\angle ABC=\\\\frac{1}{2}\\\\angle AOC$:", math: "$\\\\angle ABC=20°$" }] },',
    '      { num: 22, text: "Trójkąty prostokątne $T_1$ i $T_2$ są podobne. Przyprostokątne trójkąta $T_1$ mają długości $5$ i $12$. Przeciwprostokątna trójkąta $T_2$ ma długość $26$. Oblicz pole trójkąta $T_2$. Zapisz obliczenia.", type: "otwarte", answer: "$P_{T_2}=120$", solution: [{ step: "Przeciwprostokątna $T_1=\\\\sqrt{5^2+12^2}=13$. Skala $k=26/13=2$.", math: "" }, { step: "Pole $T_1=\\\\frac{1}{2}\\\\cdot5\\\\cdot12=30$; pole $T_2=k^2\\\\cdot30$:", math: "$P_{T_2}=4\\\\cdot30=120$" }] },',
    '      { num: 23, text: "W kartezjańskim układzie współrzędnych dane są proste $k\\\\colon y=\\\\frac{2}{3}x$ i $l\\\\colon y=-\\\\frac{3}{2}x+13$. Dokończ zdanie. Wybierz odpowiedź A albo B oraz odpowiedź 1., 2. albo 3. Proste $k$ oraz $l$: A. są prostopadłe / B. nie są prostopadłe; i przecinają się w punkcie: 1. $(-6,-4)$  2. $(6,4)$  3. $(-6,4)$.", type: "zamknięte", answer: "A, 2", solution: [{ step: "Iloczyn współczynników kierunkowych: $\\\\frac{2}{3}\\\\cdot(-\\\\frac{3}{2})=-1$ → prostopadłe → A.", math: "" }, { step: "Punkt przecięcia: $\\\\frac{2}{3}x=-\\\\frac{3}{2}x+13\\\\Rightarrow\\\\frac{13}{6}x=13\\\\Rightarrow x=6$, $y=4$:", math: "$P=(6,4)$ → 2" }] },',
    '      { num: 24, text: "W kartezjańskim układzie współrzędnych dana jest prosta $k\\\\colon y=-\\\\frac{1}{3}x+2$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Prosta $y=ax+b$ jest równoległa do prostej $k$ i przechodzi przez punkt $P=(3,5)$, gdy. A. $a=3$ i $b=4$  B. $a=-\\\\frac{1}{3}$ i $b=4$  C. $a=3$ i $b=-4$  D. $a=-\\\\frac{1}{3}$ i $b=6$", type: "zamknięte", answer: "D", solution: [{ step: "Równoległe → $a=-\\\\frac{1}{3}$. Przez $(3,5)$: $5=-\\\\frac{1}{3}\\\\cdot3+b\\\\Rightarrow b=6$:", math: "$a=-\\\\frac{1}{3},\\;b=6$" }] },',
    '      { num: 25, text: "Dany jest graniastosłup prawidłowy czworokątny, w którym krawędź podstawy ma długość $15$. Przekątna graniastosłupa jest nachylona do płaszczyzny podstawy pod kątem $\\\\alpha$ takim, że $\\\\cos\\\\alpha=\\\\frac{\\\\sqrt{2}}{3}$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Długość przekątnej tego graniastosłupa jest równa. A. $15\\\\sqrt{2}$  B. $45$  C. $5\\\\sqrt{2}$  D. 10", type: "zamknięte", answer: "B", solution: [{ step: "Przekątna podstawy $d_0=15\\\\sqrt{2}$. $\\\\cos\\\\alpha=\\\\frac{d_0}{d}$:", math: "$d=\\\\frac{15\\\\sqrt{2}}{\\\\sqrt{2}/3}=15\\\\sqrt{2}\\\\cdot\\\\frac{3}{\\\\sqrt{2}}=45$" }] },',
    '      { num: 26, text: "Dany jest ostrosłup prawidłowy czworokątny. Wysokość ściany bocznej (apotema) tego ostrosłupa jest nachylona do płaszczyzny podstawy pod kątem $30°$ i ma długość $6$. Oblicz objętość i pole powierzchni całkowitej tego ostrosłupa. Zapisz obliczenia.", type: "otwarte", answer: "$V=108$, $P_{pc}=(108+72\\\\sqrt{3})$", solution: [{ step: "Apotema $m=6$. Podstawa: $a/2=m\\\\cdot\\\\cos30°=3\\\\sqrt{3}$, więc $a=6\\\\sqrt{3}$.", math: "" }, { step: "Wysokość $h=m\\\\cdot\\\\sin30°=3$. Objętość:", math: "$V=\\\\frac{1}{3}\\\\cdot(6\\\\sqrt{3})^2\\\\cdot3=\\\\frac{1}{3}\\\\cdot108\\\\cdot3=108$" }, { step: "Pole:", math: "$P_{pc}=(6\\\\sqrt{3})^2+4\\\\cdot\\\\frac{1}{2}\\\\cdot6\\\\sqrt{3}\\\\cdot6=108+72\\\\sqrt{3}$" }] },',
    '      { num: 27, text: "W pewnym ostrosłupie prawidłowym stosunek liczby $W$ wszystkich wierzchołków do liczby $K$ wszystkich krawędzi jest równy $\\\\frac{W}{K}=\\\\frac{3}{5}$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Podstawą tego ostrosłupa jest. A. kwadrat  B. pięciokąt foremny  C. sześciokąt foremny  D. siedmiokąt foremny", type: "zamknięte", answer: "B", solution: [{ step: "Dla ostrosłupa n-kątnego: $W=n+1$, $K=2n$. $(n+1)/(2n)=3/5$:", math: "$5n+5=6n\\\\Rightarrow n=5$. Podstawa: pięciokąt foremny" }] },',
    '      { num: 28, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Wszystkich liczb naturalnych pięciocyfrowych, w których zapisie dziesiętnym występują tylko cyfry $0$, $5$, $7$ (np. $57075$, $55555$), jest. A. $5^3$  B. $2\\\\cdot4^3$  C. $2\\\\cdot3^4$  D. $3^5$", type: "zamknięte", answer: "C", solution: [{ step: "Pierwsza cyfra: 2 wybory (5 lub 7). Pozostałe 4 cyfry: po 3 wybory każda:", math: "$2\\\\cdot3^4=162$" }] },',
    '      { num: 29, text: "Na diagramie słupkowym przedstawiono ceny pomidorów (za 1 kg) w szesnastu wybranych sklepach (ceny: $5{,}05$; $5{,}60$; $5{,}70$; $6{,}00$; $6{,}30$ zł). Uzupełnij tabelę — wpisz w każdą pustą komórkę właściwą odpowiedź wybraną spośród A–E. (29.1) Mediana ceny kilograma pomidorów. (29.2) Średnia cena kilograma pomidorów. A. $5{,}80$ zł  B. $5{,}73$ zł  C. $5{,}85$ zł  D. $6{,}00$ zł  E. $5{,}70$ zł", type: "otwarte", answer: "(29.1): C (5,85 zł); (29.2): A (5,80 zł)", solution: [{ step: "(29.1) Mediana (8. i 9. wartość z 16): $\\\\frac{5{,}70+6{,}00}{2}=5{,}85$ zł.", math: "" }, { step: "(29.2) Średnia z danych odczytanych z diagramu $=5{,}80$ zł.", math: "" }] },',
    '      { num: 30, text: "Ze zbioru ośmiu liczb $\\\\{2,3,4,5,6,7,8,9\\\\}$ losujemy ze zwracaniem kolejno dwa razy po jednej liczbie. Oblicz prawdopodobieństwo zdarzenia $A$ polegającego na tym, że iloczyn wylosowanych liczb jest podzielny przez $15$. Zapisz obliczenia.", type: "otwarte", answer: "$P(A)=\\\\frac{6}{64}=\\\\frac{3}{32}$", solution: [{ step: "Iloczyn podzielny przez $15=3\\\\cdot5$: potrzebna liczba podzielna przez 5 (tylko $\\\\{5\\\\}$) i przez 3 (to $\\\\{3,6,9\\\\}$).", math: "" }, { step: "Zdarzenia sprzyjające (inkluzja-ekskluzja): $|A|=64-49-25+16=6$.", math: "$P(A)=\\\\frac{6}{64}=\\\\frac{3}{32}$" }] },',
    '      { num: 31, text: "Właściciel apteki przeanalizował dane z $30$ kolejnych dni. Liczbę $L$ klientów $n$-tego dnia opisuje funkcja $L(n)=-n^{2}+22n+279$, gdzie $1\\\\leq n\\\\leq30$. (31.1) Oceń prawdziwość stwierdzeń (P/F): (1) Łączna liczba klientów z 30 dni jest równa $L(30)$. (2) W trzecim dniu obsłużono 336 klientów. (31.2) Którego dnia obsłużono największą liczbę klientów? Oblicz tę liczbę. Zapisz obliczenia.", type: "otwarte", answer: "(31.1): F, P; (31.2): dzień 11, 400 klientów", solution: [{ step: "(31.1) $L(30)=-900+660+279=39$ to liczba klientów 30. dnia, nie łączna → F. $L(3)=-9+66+279=336$ → P.", math: "" }, { step: "(31.2) Wierzchołek paraboli: $n=\\\\frac{22}{2}=11$.", math: "$L(11)=-121+242+279=400$" }]  }',
]

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# 2023 tasks: lines 313-343 in file (1-indexed) = indices 312-342 (0-indexed)
print("Line 313 (0-idx 312):", lines[312][:70])
print("Line 343 (0-idx 342):", lines[342][:70])
print("Line 344 (0-idx 343):", lines[343][:70])

before = lines[:312]
after = lines[343:]

new_task_lines = [t + '\n' for t in new_tasks]
new_lines = before + new_task_lines + after

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f"Done! New file has {len(new_lines)} lines.")
print(f"New line 313 (0-idx 312): {new_lines[312][:70]}")
print(f"New line 344 (0-idx 343): {new_lines[343][:70]}")
