#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Replace 2024 exam fake tasks with real CKE content."""

file_path = r"E:\matematyka - strona kompedium\arkusze.html"

new_tasks = [
    '      { num: 1, text: "Dana jest nierówność $|x-1|\\\\geq 3$. Na którym rysunku poprawnie zaznaczono na osi liczbowej zbiór wszystkich liczb rzeczywistych spełniających powyższą nierówność? Wybierz właściwą odpowiedź spośród podanych. A. przedział $(-2,4)$  B. $(-\\\\infty,-2]\\\\cup[4,+\\\\infty)$  C. $[-2,4]$  D. $(-\\\\infty,-2)\\\\cup(4,+\\\\infty)$", type: "zamknięte", answer: "B", solution: [{ step: "Rozwiązujemy nierówność z wartością bezwzględną:", math: "$x-1\\\\leq -3$ lub $x-1\\\\geq 3 \\\\Rightarrow x\\\\leq -2$ lub $x\\\\geq 4$" }] },',
    '      { num: 2, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\\\left(\\\\frac{1}{16}\\\\right)^{8}\\\\cdot 8^{16}$ jest równa. A. $2^{24}$  B. $2^{16}$  C. $2^{12}$  D. $2^{8}$", type: "zamknięte", answer: "B", solution: [{ step: "Sprowadzamy do potęg liczby 2:", math: "$(2^{-4})^8\\\\cdot(2^3)^{16}=2^{-32}\\\\cdot 2^{48}=2^{16}$" }] },',
    '      { num: 3, text: "Wykaż, że dla każdej liczby naturalnej $n\\\\geq 1$ liczba $n^{2}+(n+1)^{2}+(n+2)^{2}$ przy dzieleniu przez $3$ daje resztę $2$.", type: "otwarte", answer: "$n^2+(n+1)^2+(n+2)^2=3(n^2+2n+1)+2$", solution: [{ step: "Przekształcamy wyrażenie:", math: "$n^2+(n+1)^2+(n+2)^2=3n^2+6n+5=3(n^2+2n+1)+2$" }, { step: "Wynik jest postaci $3k+2$, co należało wykazać.", math: "" }] },',
    '      { num: 4, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\\\log_{\\\\sqrt{3}} 9$ jest równa. A. 2  B. 3  C. 4  D. 9", type: "zamknięte", answer: "C", solution: [{ step: "Z definicji logarytmu: $(\\\\sqrt{3})^x=9$:", math: "$(3^{1/2})^x=3^2 \\\\Rightarrow x/2=2 \\\\Rightarrow x=4$" }] },',
    '      { num: 5, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Dla każdej liczby rzeczywistej $a$ i $b$ wartość wyrażenia $(2a+b)^{2}-(2a-b)^{2}$ jest równa wartości wyrażenia. A. $8a^{2}$  B. $8ab$  C. $-8ab$  D. $2b^{2}$", type: "zamknięte", answer: "B", solution: [{ step: "Wzór $p^2-q^2=(p+q)(p-q)$:", math: "$(4a)(2b)=8ab$" }] },',
    '      { num: 6, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Zbiorem wszystkich rozwiązań nierówności $1-\\\\frac{3}{2}x<-\\\\frac{2}{3}x$ jest przedział. A. $(-\\\\infty,-\\\\frac{2}{3})$  B. $(-\\\\infty,\\\\frac{2}{3})$  C. $(-\\\\frac{2}{3},+\\\\infty)$  D. $(\\\\frac{6}{5},+\\\\infty)$", type: "zamknięte", answer: "D", solution: [{ step: "Przekształcamy:", math: "$1<\\\\frac{3}{2}x-\\\\frac{2}{3}x=\\\\frac{5}{6}x \\\\Rightarrow x>\\\\frac{6}{5}$" }] },',
    '      { num: 7, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Równanie $\\\\frac{x+1}{(x+2)(x-3)}=0$ w zbiorze liczb rzeczywistych. A. nie ma rozwiązania.  B. ma dokładnie jedno rozwiązanie: $(-1)$.  C. ma dokładnie dwa rozwiązania: $(-2)$ oraz $3$.  D. ma dokładnie trzy rozwiązania: $(-1)$, $(-2)$ oraz $3$.", type: "zamknięte", answer: "B", solution: [{ step: "Ułamek $=0$ gdy licznik $=0$, a mianownik $\\\\neq 0$:", math: "$x+1=0\\\\Rightarrow x=-1$; $x\\\\neq -2$, $x\\\\neq 3$" }] },',
    '      { num: 8, text: "Dany jest wielomian $W(x)=3x^{3}+6x^{2}+9x$. Oceń prawdziwość poniższych stwierdzeń (P/F): (1) Wielomian $W$ jest iloczynem wielomianów $F(x)=3x$ i $G(x)=x^{2}+2x+3$. (2) Liczba $(-1)$ jest rozwiązaniem równania $W(x)=0$.", type: "zamknięte", answer: "P, F", solution: [{ step: "Sprawdzamy rozkład: $3x(x^2+2x+3)=3x^3+6x^2+9x$ ✓ → P.", math: "" }, { step: "$W(-1)=-3+6-9=-6\\\\neq 0$ → F.", math: "" }] },',
    '      { num: 9, text: "Rozwiąż równanie $x^{3}-2x^{2}-3x+6=0$. Zapisz obliczenia.", type: "otwarte", answer: "$x=2$, $x=\\\\sqrt{3}$, $x=-\\\\sqrt{3}$", solution: [{ step: "Grupowanie wyrazów:", math: "$x^2(x-2)-3(x-2)=0\\\\Rightarrow(x-2)(x^2-3)=0$" }, { step: "Rozwiązania:", math: "$x=2$ lub $x=\\\\pm\\\\sqrt{3}$" }] },',
    '      { num: 10, text: "W październiku 2022 roku założono dwa sady, w których posadzono łącznie 1960 drzew. Po roku uschło 5% drzew w pierwszym sadzie i 10% drzew w drugim sadzie. Liczba drzew pozostałych w drugim sadzie stanowiła 60% liczby drzew pozostałych w pierwszym sadzie. Niech $x$ oraz $y$ oznaczają liczby drzew posadzonych odpowiednio w pierwszym i drugim sadzie. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Układem równań, którego poprawne rozwiązanie prowadzi do obliczenia $x$ i $y$, jest. A. $\\\\begin{cases}x+y=1960\\\\\\\\0{,}6\\\\cdot0{,}95x=0{,}9y\\\\end{cases}$  B. $\\\\begin{cases}x+y=1960\\\\\\\\0{,}95x=0{,}6\\\\cdot0{,}9y\\\\end{cases}$  C. $\\\\begin{cases}x+y=1960\\\\\\\\0{,}05x=0{,}6\\\\cdot0{,}1y\\\\end{cases}$  D. $\\\\begin{cases}x+y=1960\\\\\\\\0{,}4\\\\cdot0{,}95x=0{,}9y\\\\end{cases}$", type: "zamknięte", answer: "A", solution: [{ step: "Pozostałe drzewa: $0{,}95x$ (sad 1) i $0{,}9y$ (sad 2). Warunek: $0{,}9y=0{,}6\\\\cdot0{,}95x$", math: "$0{,}9y=0{,}6\\\\cdot 0{,}95x$" }] },',
    '      { num: 11, text: "Na rysunku w kartezjańskim układzie współrzędnych $(x,y)$ przedstawiono dwie proste równoległe. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Układem równań, którego interpretację geometryczną przedstawiono na rysunku, jest. A. $\\\\begin{cases}y=\\\\frac{3}{2}x+3\\\\\\\\y=\\\\frac{3}{2}x-1\\\\end{cases}$  B. $\\\\begin{cases}y=\\\\frac{3}{2}x+3\\\\\\\\y=-\\\\frac{2}{3}x-1\\\\end{cases}$  C. $\\\\begin{cases}y=-\\\\frac{3}{2}x+3\\\\\\\\y=-\\\\frac{3}{2}x-1\\\\end{cases}$  D. $\\\\begin{cases}y=-\\\\frac{3}{2}x-3\\\\\\\\y=\\\\frac{3}{2}x+1\\\\end{cases}$", type: "zamknięte", answer: "A", solution: [{ step: "Równoległe proste mają równe współczynniki kierunkowe.", math: "$a_1=a_2=\\\\frac{3}{2}$, $b_1=3$, $b_2=-1$" }] },',
    '      { num: 12, text: "Funkcja liniowa $f$ jest określona wzorem $f(x)=(-2k+3)x+k-1$, gdzie $k\\\\in\\\\mathbb{R}$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Funkcja $f$ jest malejąca dla każdej liczby $k$ należącej do przedziału. A. $(-\\\\infty,1)$  B. $(-\\\\infty,-\\\\frac{3}{2})$  C. $(1,+\\\\infty)$  D. $(\\\\frac{3}{2},+\\\\infty)$", type: "zamknięte", answer: "D", solution: [{ step: "Funkcja liniowa malejąca gdy współczynnik kierunkowy $<0$:", math: "$-2k+3<0\\\\Rightarrow k>\\\\frac{3}{2}$" }] },',
    '      { num: 13, text: "Funkcje liniowe $f$ i $g$ są określone wzorami $f(x)=3x+6$ i $g(x)=ax+7$ i mają to samo miejsce zerowe. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Współczynnik $a$ we wzorze funkcji $g$ jest równy. A. $-\\\\frac{7}{2}$  B. $-\\\\frac{2}{7}$  C. $\\\\frac{2}{7}$  D. $\\\\frac{7}{2}$", type: "zamknięte", answer: "D", solution: [{ step: "Wyznaczamy miejsce zerowe $f$, podstawiamy do $g(x)=0$:", math: "$3x+6=0\\\\Rightarrow x=-2$; $a(-2)+7=0\\\\Rightarrow a=\\\\frac{7}{2}$" }] },',
    '      { num: 14, text: "W kartezjańskim układzie współrzędnych przedstawiono fragment paraboli — wykres funkcji kwadratowej $f$. Wierzchołek paraboli ma współrzędne $(1,9)$, parabola przecina oś $Ox$ w punktach $(-2,0)$ i $(4,0)$. (14.1) Uzupełnij zdanie. Zbiorem wszystkich rozwiązań nierówności $f(x)\\\\geq 0$ jest przedział ... (14.2) Wzór funkcji kwadratowej $f$: A. $f(x)=-(x+1)^2-9$  B. $f(x)=-(x-1)^2+9$  C. $f(x)=-(x-1)^2-9$  D. $f(x)=-(x+1)^2+9$. (14.3) Dla funkcji $f$ prawdziwa jest równość: A. $f(-4)=f(6)$  B. $f(-4)=f(5)$  C. $f(-4)=f(4)$  D. $f(-4)=f(7)$. (14.4) Funkcje $g(x)=f(x+3)$ i $h(x)=f(-x)$ — przyporządkuj każdej z nich fragment wykresu spośród A–F.", type: "otwarte", answer: "(14.1): $[-2,4]$; (14.2): B; (14.3): A; (14.4): g: A, h: E", solution: [{ step: "(14.1) $f(x)\\\\geq 0$ między miejscami zerowymi:", math: "$x\\\\in[-2,4]$" }, { step: "(14.2) Postać kanoniczna z wierzchołkiem $(1,9)$:", math: "$f(x)=-(x-1)^2+9$" }, { step: "(14.3) Oś symetrii $x=1$: $\\\\frac{-4+6}{2}=1$:", math: "$f(-4)=f(6)$, odp. A" }, { step: "(14.4) $g(x)=f(x+3)$ — przesunięcie o 3 w lewo; $h(x)=f(-x)$ — odbicie.", math: "" }] },',
    '      { num: 15, text: "Ciąg $(a_n)$ jest określony wzorem $a_n=(-1)^n\\\\cdot(n-5)$ dla każdej liczby naturalnej $n\\\\geq 1$. Oceń prawdziwość poniższych stwierdzeń (P/F): (1) Pierwszy wyraz ciągu $(a_n)$ jest dwa razy większy od trzeciego wyrazu. (2) Wszystkie wyrazy ciągu $(a_n)$ są dodatnie.", type: "zamknięte", answer: "P, F", solution: [{ step: "$a_1=(-1)^1\\\\cdot(1-5)=4$, $a_3=(-1)^3\\\\cdot(3-5)=2$. $4=2\\\\cdot 2$ → P.", math: "" }, { step: "$a_2=(-1)^2\\\\cdot(2-5)=-3<0$ → nie wszystkie dodatnie → F.", math: "" }] },',
    '      { num: 16, text: "Trzywyrazowy ciąg $(12, 6, 2m-1)$ jest geometryczny. Dokończ zdanie. Wybierz odpowiedź A albo B oraz odpowiedź 1., 2. albo 3. Ten ciąg jest: A. rosnący / B. malejący. Oraz: 1. $m=\\\\frac{1}{2}$  2. $m=2$  3. $m=3$", type: "zamknięte", answer: "B, 2", solution: [{ step: "Iloraz $q=\\\\frac{6}{12}=\\\\frac{1}{2}$; $2m-1=3\\\\Rightarrow m=2$; ciąg malejący.", math: "" }] },',
    '      { num: 17, text: "Ciąg arytmetyczny $(a_n)$ jest określony dla każdej liczby naturalnej $n\\\\geq 1$. Trzeci wyraz tego ciągu jest równy $(-1)$, a suma piętnastu początkowych wyrazów jest równa $(-165)$. Oblicz różnicę tego ciągu. Zapisz obliczenia.", type: "otwarte", answer: "$r=-2$", solution: [{ step: "Układ: $a_1+2r=-1$ i $\\\\frac{15}{2}(2a_1+14r)=-165$:", math: "$a_1+2r=-1;\\\\;a_1+7r=-11$" }, { step: "Odejmując:", math: "$5r=-10\\\\Rightarrow r=-2$" }] },',
    '      { num: 18, text: "W kartezjańskim układzie współrzędnych zaznaczono kąt o mierze $\\\\alpha$ taki, że $\\\\mathrm{tg}\\\\,\\\\alpha=-3$ oraz $90°<\\\\alpha<180°$. Uzupełnij zdanie. Wybierz dwie właściwe odpowiedzi spośród A–F. A. $\\\\sin\\\\alpha<0$  B. $\\\\sin\\\\alpha\\\\cdot\\\\cos\\\\alpha<0$  C. $\\\\sin\\\\alpha\\\\cdot\\\\cos\\\\alpha>0$  D. $\\\\cos\\\\alpha>0$  E. $\\\\sin\\\\alpha=-\\\\frac{1}{3}\\\\cos\\\\alpha$  F. $\\\\sin\\\\alpha=-3\\\\cos\\\\alpha$. Prawdziwe są zależności: ... oraz ...", type: "zamknięte", answer: "B, F", solution: [{ step: "W II ćwiartce: $\\\\sin\\\\alpha>0$, $\\\\cos\\\\alpha<0$ → iloczyn $<0$ → B.", math: "" }, { step: "$\\\\mathrm{tg}\\\\,\\\\alpha=\\\\frac{\\\\sin\\\\alpha}{\\\\cos\\\\alpha}=-3\\\\Rightarrow\\\\sin\\\\alpha=-3\\\\cos\\\\alpha$ → F.", math: "" }] },',
    '      { num: 19, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\\\sin^{3}20°+\\\\cos^{2}20°\\\\cdot\\\\sin20°$ jest równa. A. $\\\\cos20°$  B. $\\\\sin20°$  C. $\\\\mathrm{tg}\\\\,20°$  D. $\\\\sin20°\\\\cdot\\\\cos20°$", type: "zamknięte", answer: "B", solution: [{ step: "Wyłączamy $\\\\sin20°$ i stosujemy jedynkę trygonometryczną:", math: "$\\\\sin20°(\\\\sin^220°+\\\\cos^220°)=\\\\sin20°\\\\cdot 1=\\\\sin20°$" }] },',
    '      { num: 20, text: "Dany jest trójkąt $KLM$, w którym $|KM|=a$, $|LM|=b$ i $a\\\\neq b$. Dwusieczna kąta $KML$ przecina bok $KL$ w punkcie $N$ takim, że $|KN|=c$, $|NL|=d$, $|MN|=e$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. W trójkącie $KLM$ prawdziwa jest równość. A. $a\\\\cdot b=c\\\\cdot d$  B. $a\\\\cdot d=b\\\\cdot c$  C. $a\\\\cdot c=b\\\\cdot d$  D. $a\\\\cdot b=e^2$", type: "zamknięte", answer: "B", solution: [{ step: "Twierdzenie o dwusiecznej: $\\\\frac{KN}{NL}=\\\\frac{KM}{LM}$:", math: "$\\\\frac{c}{d}=\\\\frac{a}{b}\\\\Rightarrow a\\\\cdot d=b\\\\cdot c$" }] },',
    '      { num: 21, text: "Dany jest równoległobok o bokach długości $3$ i $4$ oraz o kącie między nimi o mierze $120°$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Pole tego równoległoboku jest równe. A. $12$  B. $12\\\\sqrt{3}$  C. $6$  D. $6\\\\sqrt{3}$", type: "zamknięte", answer: "D", solution: [{ step: "Pole = $a\\\\cdot b\\\\cdot\\\\sin(\\\\text{kąt})$; $\\\\sin120°=\\\\frac{\\\\sqrt{3}}{2}$:", math: "$P=3\\\\cdot4\\\\cdot\\\\frac{\\\\sqrt{3}}{2}=6\\\\sqrt{3}$" }] },',
    '      { num: 22, text: "W trójkącie $ABC$ wpisanym w okrąg o środku $S$ kąt $ACB$ ma miarę $42°$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Miara kąta ostrego $BAS$ jest równa. A. $42°$  B. $45°$  C. $48°$  D. $69°$", type: "zamknięte", answer: "C", solution: [{ step: "Kąt środkowy $ASB=2\\\\cdot42°=84°$. Trójkąt $ASB$ równoramienny ($SA=SB=r$):", math: "$\\\\angle BAS=\\\\frac{180°-84°}{2}=48°$" }] },',
    '      { num: 23, text: "W kartezjańskim układzie współrzędnych proste $k$ oraz $l$ są określone równaniami $k\\\\colon y=(m+1)x+7$ oraz $l\\\\colon y=-2x+7$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Proste $k$ oraz $l$ są prostopadłe, gdy liczba $m$ jest równa. A. $-\\\\frac{1}{2}$  B. $\\\\frac{1}{2}$  C. $-3$  D. $1$", type: "zamknięte", answer: "A", solution: [{ step: "Warunek prostopadłości $a_1\\\\cdot a_2=-1$:", math: "$(m+1)\\\\cdot(-2)=-1\\\\Rightarrow m+1=\\\\frac{1}{2}\\\\Rightarrow m=-\\\\frac{1}{2}$" }] },',
    '      { num: 24, text: "W kartezjańskim układzie współrzędnych dany jest równoległobok $ABCD$, w którym $A=(-2,6)$ i $B=(10,2)$. Przekątne $AC$ i $BD$ przecinają się w punkcie $P=(6,7)$. Oblicz długość boku $BC$ tego równoległoboku. Zapisz obliczenia.", type: "otwarte", answer: "$|BC|=\\\\sqrt{52}=2\\\\sqrt{13}$", solution: [{ step: "Środek przekątnych to $P$; $C=2P-A=(14,8)$", math: "$C=(2\\\\cdot6-(-2),\\;2\\\\cdot7-6)=(14,8)$" }, { step: "Długość $BC$:", math: "$|BC|=\\\\sqrt{(14-10)^2+(8-2)^2}=\\\\sqrt{16+36}=\\\\sqrt{52}$" }] },',
    '      { num: 25, text: "Wysokość graniastosłupa prawidłowego sześciokątnego jest równa $6$. Pole podstawy tego graniastosłupa jest równe $15\\\\sqrt{3}$. (25.1) Pole jednej ściany bocznej tego graniastosłupa jest równe: A. $36\\\\sqrt{10}$  B. $60$  C. $6\\\\sqrt{10}$  D. $360$. (25.2) Kąt nachylenia najdłuższej przekątnej graniastosłupa prawidłowego sześciokątnego do płaszczyzny podstawy jest zaznaczony na rysunku (wybierz właściwy z A–D).", type: "zamknięte", answer: "25.1: C; 25.2: D", solution: [{ step: "Pole podstawy sześciokąta foremnego $=\\\\frac{3\\\\sqrt{3}}{2}a^2=15\\\\sqrt{3}\\\\Rightarrow a^2=10\\\\Rightarrow a=\\\\sqrt{10}$.", math: "" }, { step: "(25.1) Pole ściany bocznej $=a\\\\cdot h=\\\\sqrt{10}\\\\cdot6=6\\\\sqrt{10}$. Odp. C.", math: "" }, { step: "(25.2) Kąt między przekątną a podstawą — odp. D.", math: "" }] },',
    '      { num: 26, text: "Ostrosłup $F_1$ jest podobny do ostrosłupa $F_2$. Objętość $F_1$ jest równa $64$. Objętość $F_2$ jest równa $512$. Uzupełnij zdanie. Stosunek pola powierzchni całkowitej ostrosłupa $F_2$ do pola powierzchni całkowitej ostrosłupa $F_1$ jest równy ...", type: "otwarte", answer: "$4$", solution: [{ step: "Skala podobieństwa $k$: $k^3=512/64=8\\\\Rightarrow k=2$. Stosunek pól $=k^2$:", math: "$k^2=4$" }] },',
    '      { num: 27, text: "Rozważamy wszystkie kody czterocyfrowe utworzone tylko z cyfr $1, 3, 6, 8$, przy czym każda cyfra występuje dokładnie jeden raz. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba wszystkich takich kodów jest równa. A. $4$  B. $10$  C. $24$  D. $16$", type: "zamknięte", answer: "C", solution: [{ step: "Liczba permutacji 4 różnych cyfr:", math: "$4!=24$" }] },',
    '      { num: 28, text: "Średnia arytmetyczna trzech liczb: $a, b, c$, jest równa $9$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Średnia arytmetyczna sześciu liczb: $a, a, b, b, c, c$ jest równa. A. $9$  B. $6$  C. $4{,}5$  D. $18$", type: "zamknięte", answer: "A", solution: [{ step: "Suma $a+b+c=27$; suma 6 liczb $=2\\\\cdot27=54$; średnia $=54/6$:", math: "$\\\\bar{x}=9$" }] },',
    '      { num: 29, text: "Na diagramie słupkowym przedstawiono wyniki sprawdzianu z matematyki w pewnej klasie maturalnej (oceny 1–6 na osi poziomej, liczba uczniów na osi pionowej). Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Mediana ocen uzyskanych z tego sprawdzianu jest równa. A. $4{,}5$  B. $4$  C. $3{,}5$  D. $3$", type: "zamknięte", answer: "C", solution: [{ step: "Odczytujemy liczby uczniów z diagramu i wyznaczamy środkową wartość:", math: "$\\\\text{mediana}=3{,}5$" }] },',
    '      { num: 30, text: "Dany jest pięcioelementowy zbiór $K=\\\\{5,6,7,8,9\\\\}$. Ze zbioru $K$ losujemy ze zwracaniem kolejno dwa razy po jednej liczbie i zapisujemy je w kolejności losowania. Oblicz prawdopodobieństwo zdarzenia $A$ polegającego na tym, że suma wylosowanych liczb jest liczbą parzystą. Zapisz obliczenia.", type: "otwarte", answer: "$P(A)=\\\\frac{13}{25}$", solution: [{ step: "Liczba zdarzeń elementarnych: $5\\\\cdot5=25$.", math: "" }, { step: "Suma parzysta: obie parzyste ($\\{6,8\\}$: 2) lub obie nieparzyste ($\\{5,7,9\\}$: 3). Sprzyjające: $2^2+3^2=4+9=13$.", math: "$P(A)=\\\\frac{13}{25}$" }] },',
    '      { num: 31, text: "W schronisku dla zwierząt na płaskiej powierzchni należy zbudować ogrodzenie z siatki wydzielające trzy identyczne wybiegi o wspólnych ścianach wewnętrznych. Podstawą każdego wybiegu jest prostokąt o wymiarach $x$ i $y$ (trzy wybiegi obok siebie). Do ogrodzenia zużyć należy $36$ metrów bieżących siatki. Oblicz wymiary $x$ i $y$ jednego wybiegu, przy których suma pól podstaw tych trzech wybiegów będzie największa. Zapisz obliczenia.", type: "otwarte", answer: "$x=4{,}5$ m, $y=3$ m", solution: [{ step: "Warunek na długość siatki: $4x+6y=36$:", math: "$y=6-\\\\frac{2}{3}x$" }, { step: "Suma pól $P=3xy=-2x^2+18x$. Wierzchołek paraboli:", math: "$x=\\\\frac{18}{4}=4{,}5$; $y=3$" }] }',
]

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# 2024 tasks: lines 270-300 (file lines, 1-indexed) = indices 269-299(0-indexed)
# Verify:
print("Line 270 (0-idx 269):", lines[269][:70])
print("Line 300 (0-idx 299):", lines[299][:70])
print("Line 301 (0-idx 300):", lines[300][:70])

before = lines[:269]
after = lines[300:]

new_task_lines = [t + '\n' for t in new_tasks]
new_lines = before + new_task_lines + after

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f"Done! New file has {len(new_lines)} lines.")
print(f"New line 270 (0-idx 269): {new_lines[269][:70]}")
print(f"New line 301 (0-idx 300): {new_lines[300][:70]}")
