$file = "E:\matematyka - strona kompedium\arkusze.html"
$content = Get-Content $file -Raw -Encoding UTF8
$lines = Get-Content $file -Encoding UTF8

$newTasks = @(
'      { num: 1, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $(\\sqrt{32} - \\sqrt{2})^{2}$ jest równa. A. 16  B. 18  C. 30  D. 34", type: "zamknięte", answer: "B", solution: [{ step: "Upraszczamy:", math: "$(\\sqrt{32}-\\sqrt{2})^2=(4\\sqrt{2}-\\sqrt{2})^2=(3\\sqrt{2})^2=18$" }] },',
'      { num: 2, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\frac{5^{12}+5^{13}+5^{14}}{5^{12}}$ jest równa. A. 30  B. 31  C. 512  D. 527", type: "zamknięte", answer: "B", solution: [{ step: "Wyciągamy $5^{12}$:", math: "$\\frac{5^{12}(1+5+25)}{5^{12}}=31$" }] },',
'      { num: 3, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Liczba $\\log_{3}108 - 2\\log_{3}2$ jest równa. A. 3  B. 9  C. $\\log_{3}104$  D. $2\\log_{3}54$", type: "zamknięte", answer: "A", solution: [{ step: "Korzystamy z własności logarytmów:", math: "$\\log_{3}108-\\log_{3}4=\\log_{3}27=3$" }] },',
'      { num: 4, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Dla każdej liczby rzeczywistej $x$ wartość wyrażenia $(3x+2)^{2}-(2x-3)^{2}$ jest równa wartości wyrażenia. A. $5x^{2}-5$  B. $5x^{2}+13$  C. $5x^{2}+24x-5$  D. $5x^{2}+24x-13$", type: "zamknięte", answer: "C", solution: [{ step: "Rozwijamy wzory skróconego mnożenia:", math: "$(9x^2+12x+4)-(4x^2-12x+9)=5x^2+24x-5$" }] },',
'      { num: 5, text: "Wykaż, że dla każdej nieparzystej liczby naturalnej $n$ liczba $3n^{2}+2n+7$ jest podzielna przez $4$.", type: "otwarte", answer: "$n=2l+1 \\Rightarrow 3n^2+2n+7=4(3l^2+4l+3)$", solution: [{ step: "Nieparzysta $n=2l+1$, $l\\in\\mathbb{Z}$:", math: "$3(2l+1)^2+2(2l+1)+7=12l^2+16l+12=4(3l^2+4l+3)$" }, { step: "Wynik jest wielokrotnością 4.", math: "" }] },',
'      { num: 6, text: "Dana jest nierówność $3-2(1-2x)\\geq 2x-17$. Na którym rysunku poprawnie zaznaczono na osi liczbowej zbiór wszystkich rozwiązań tej nierówności? A. $[3,+\\infty)$  B. $(3,+\\infty)$  C. $(-9,+\\infty)$  D. $[-9,+\\infty)$", type: "zamknięte", answer: "D", solution: [{ step: "Uproszczamy:", math: "$3-2+4x\\geq 2x-17 \\Rightarrow 2x\\geq -18 \\Rightarrow x\\geq -9$" }] },',
'      { num: 7, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Równanie $2x(x+3)(x^{2}+25)=0$ w zbiorze liczb rzeczywistych ma dokładnie. A. dwa rozwiązania: $(-3)$ oraz $0$.  B. dwa rozwiązania: $(-3)$ oraz $2$.  C. trzy rozwiązania: $(-5)$, $(-3)$ oraz $0$.  D. cztery rozwiązania: $(-5)$, $(-3)$, $0$ oraz $5$.", type: "zamknięte", answer: "A", solution: [{ step: "$x^2+25>0$ dla każdego $x\\in\\mathbb{R}$, więc:", math: "$2x=0$ lub $x+3=0$, tzn. $x=0$ lub $x=-3$" }] },',
'      { num: 8, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Dla każdej liczby rzeczywistej $x$ różnej od $(-2)$ oraz różnej od $0$ wartość wyrażenia $\\frac{x^{2}+x}{x^{2}+4x+4}\\cdot\\frac{x+2}{x}$ jest równa wartości wyrażenia. A. $\\frac{x+2}{4x+4}$  B. $\\frac{x+1}{4x+5}$  C. $\\frac{x+1}{x+2}$  D. $\\frac{2x}{x+2}$", type: "zamknięte", answer: "C", solution: [{ step: "Rozkładamy:", math: "$\\frac{x(x+1)}{(x+2)^2}\\cdot\\frac{x+2}{x}=\\frac{x+1}{x+2}$" }] },',
'      { num: 9, text: "Zarząd firmy wydzielił z budżetu kwotę 1 200 000 złotych łącznie na projekty badawcze dla dwóch zespołów: A i B. W pierwszym półroczu oba zespoły wykorzystały łącznie 146 700 złotych – zespół A wykorzystał 13% przyznanych mu środków, a zespół B wykorzystał 11% przyznanych mu środków. Oblicz kwotę przyznaną zespołowi A na realizację projektu badawczego.", type: "otwarte", answer: "735 000 zł", solution: [{ step: "Niech $a$ – kwota A, to $b=1200000-a$. Równanie:", math: "$0{,}13a+0{,}11(1200000-a)=146700$" }, { step: "Rozwiązujemy:", math: "$0{,}02a=14700 \\Rightarrow a=735000$ zł" }] },',
'      { num: 10, text: "Rozwiąż nierówność $3(2x^{2}+1)<11x$. Zapisz obliczenia.", type: "otwarte", answer: "$x\\in\\left(\\frac{1}{3},\\frac{3}{2}\\right)$", solution: [{ step: "Przekształcamy:", math: "$6x^2-11x+3<0$" }, { step: "$\\Delta=121-72=49$, $x_1=\\frac{1}{3}$, $x_2=\\frac{3}{2}$:", math: "$x\\in\\left(\\frac{1}{3},\\frac{3}{2}\\right)$" }] },',
'      { num: 11, text: "Funkcja $f$ jest określona następująco: $f(x)=\\begin{cases}x+5 & \\text{dla } x\\in[-4,-2]\\\\3 & \\text{dla } x\\in(-2,2]\\\\-3x+9 & \\text{dla } x\\in(2,4)\\end{cases}$. Uzupełnij zdania. 1. Dziedziną funkcji $f$ jest przedział ... 2. Zbiorem wartości funkcji $f$ jest przedział ... 3. Zbiorem argumentów, dla których $f>0$, jest przedział ... 4. Zbiorem rozwiązań równania $f(x)=3$ jest przedział ...", type: "otwarte", answer: "1. $[-4,4)$; 2. $(-3,3]$; 3. $[-4,3)$; 4. $[-2,2]$", solution: [{ step: "Dziedzina: $[-4,4)$; Wartości: $(-3,3]$", math: "" }, { step: "$f(x)>0$: gałąź 3 zeruje się dla $x=3$, więc $[-4,3)$", math: "" }, { step: "$f(x)=3$: gałąź 1: $x=-2$; gałąź 2: całe $(-2,2]$; gałąź 3: $x=2$ wykluczone", math: "$[-2,2]$" }] },',
'      { num: 12, text: "W kartezjańskim układzie współrzędnych przedstawiono fragment paraboli będącej wykresem funkcji kwadratowej $f$. Wierzchołek paraboli ma współrzędne $(3,6)$, a parabola przecina oś $Oy$ w punkcie $(0,3)$. (12.1) Wyznacz wzór funkcji $f$ w postaci kanonicznej. Zapisz obliczenia. (12.2) Osią symetrii wykresu funkcji $f$ jest prosta o równaniu: A. $x=3$  B. $x=-3$  C. $y=6$  D. $y=-6$. (12.3) Funkcja $g$ jest określona wzorem $g(x)=f(x)-3$. Liczby $x_1$ oraz $x_2$ są różnymi miejscami zerowymi funkcji $g$. Suma $x_1+x_2$ jest równa:", type: "otwarte", answer: "12.1: $f(x)=-\\frac{1}{3}(x-3)^2+6$; 12.2: A ($x=3$); 12.3: $6$", solution: [{ step: "12.1: $f(x)=a(x-3)^2+6$; po podstawieniu $(0,3)$:", math: "$3=9a+6 \\Rightarrow a=-\\frac{1}{3}$" }, { step: "12.2: Wierzchołek w $x=3$, więc oś $x=3$. Odp. A.", math: "" }, { step: "12.3: $g(x)=-\\frac{1}{3}(x-3)^2+3=0\\Rightarrow(x-3)^2=9 \\Rightarrow x_1=0,\\,x_2=6$:", math: "$x_1+x_2=6$" }] },',
'      { num: 13, text: "Funkcja liniowa $f$ jest określona wzorem $f(x)=(3-m)x-4$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Funkcja $f$ nie ma miejsca zerowego dla $m$ równego. A. $(-3)$  B. $0$  C. $3$  D. $4$", type: "zamknięte", answer: "C", solution: [{ step: "Brak miejsca zerowego gdy $f$ jest funkcją stałą, tj. $3-m=0$:", math: "$m=3$" }] },',
'      { num: 14, text: "Ciąg $(a_n)$ jest określony następująco: $a_1=2$ oraz $a_{n+1}=2a_n+1$ dla każdej liczby naturalnej $n\\geq 1$. (14.1) Trzeci wyraz ciągu $(a_n)$ jest równy: A. 4  B. 5  C. 7  D. 11. (14.2) Oceń prawdziwość stwierdzeń (P/F): (1) Ciąg $(a_n)$ jest arytmetyczny.  (2) Ciąg $(a_n)$ jest geometryczny.", type: "zamknięte", answer: "14.1: D  14.2: F, F", solution: [{ step: "14.1: $a_2=5$, $a_3=11$. Odp. D.", math: "" }, { step: "14.2: Ciąg: 2,5,11,23... Różnice i ilorazy niestałe — oba F.", math: "" }] },',
'      { num: 15, text: "Wyznacz wartość $m$, dla której trzywyrazowy ciąg $(2m+11,\\ m^{2}+3,\\ 5-m)$ jest arytmetyczny i malejący. Zapisz obliczenia.", type: "otwarte", answer: "$m=\\frac{5}{2}$", solution: [{ step: "Warunek arytmetyczny: $2(m^2+3)=(2m+11)+(5-m)$:", math: "$2m^2-m-10=0 \\Rightarrow m_1=\\frac{5}{2},\\,m_2=-2$" }, { step: "Sprawdzamy: dla $m=\\frac{5}{2}$ ciąg jest malejący. ✓", math: "" }] },',
'      { num: 16, text: "Dany jest ciąg geometryczny $(a_n)$ określony dla każdej liczby naturalnej $n\\geq 1$, w którym $a_1=27$ oraz $a_2=9$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Czwarty wyraz ciągu $(a_n)$ jest równy. A. $\\frac{1}{3}$  B. $1$  C. $3$  D. $729$", type: "zamknięte", answer: "B", solution: [{ step: "Iloraz: $q=\\frac{1}{3}$. Wzór:", math: "$a_4=27\\cdot\\left(\\frac{1}{3}\\right)^3=1$" }] },',
'      { num: 17, text: "Kąt $\\alpha$ jest ostry i spełnia warunek $\\sqrt{3}\\,\\mathrm{tg}\\,\\alpha=2\\sin\\alpha$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Cosinus kąta $\\alpha$ jest równy. A. $\\frac{1}{2}$  B. $\\frac{\\sqrt{2}}{2}$  C. $\\frac{\\sqrt{3}}{2}$  D. $\\frac{\\sqrt{3}}{3}$", type: "zamknięte", answer: "C", solution: [{ step: "Dla $\\sin\\alpha\\neq 0$: $\\sqrt{3}\\cdot\\frac{\\sin\\alpha}{\\cos\\alpha}=2\\sin\\alpha$:", math: "$\\cos\\alpha=\\frac{\\sqrt{3}}{2}$" }] },',
'      { num: 18, text: "Dany jest trójkąt prostokątny $ABC$, w którym bok $BC$ jest przeciwprostokątną, przyprostokątna $AB$ ma długość $6$, a środkowa $CD$ ma długość $5$ ($D$ – środek $AB$). Kąt $ADC=\\alpha$, kąt $ABC=\\beta$. (18.1) Tangens kąta $\\alpha$ jest równy: A. $\\frac{2}{3}$  B. $\\frac{3}{4}$  C. $\\frac{4}{5}$  D. $\\frac{4}{3}$. (18.2) Sinus kąta $\\beta$ jest równy: A. $\\frac{2}{\\sqrt{13}}$  B. $\\frac{3}{\\sqrt{13}}$  C. $\\frac{5}{2\\sqrt{13}}$  D. $\\frac{4}{5}$", type: "zamknięte", answer: "18.1: D  18.2: A", solution: [{ step: "18.1: $AD=3$, $AC=4$ (z Pitagorasa w $\\triangle ACD$). $\\mathrm{tg}\\,\\alpha=\\frac{AC}{AD}=\\frac{4}{3}$. Odp. D.", math: "" }, { step: "18.2: $BC=2\\sqrt{13}$. $\\sin\\beta=\\frac{AC}{BC}=\\frac{4}{2\\sqrt{13}}=\\frac{2}{\\sqrt{13}}$. Odp. A.", math: "" }] },',
'      { num: 19, text: "Punkty $A$, $B$ oraz $C$ leżą na okręgu o środku w punkcie $O$. Miara kąta $BCA$ jest równa $50°$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Miara kąta ostrego $ABO$ jest równa. A. $20°$  B. $35°$  C. $40°$  D. $50°$", type: "zamknięte", answer: "C", solution: [{ step: "Kąt środkowy $BOA=2\\cdot 50°=100°$. Trójkąt $OAB$ równoramienny:", math: "$\\angle OBA=\\frac{180°-100°}{2}=40°$" }] },',
'      { num: 20, text: "W trójkącie równoramiennym $ABC$ dane są: $|AC|=|BC|=4$ i $|AB|=3$. Na boku $BC$ wybrano punkt $D$, że trójkąty $ABC$ i $BDA$ są podobne. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Odcinek $BD$ ma długość. A. $2$  B. $2{,}25$  C. $2{,}5$  D. $3$", type: "zamknięte", answer: "B", solution: [{ step: "Podobieństwo $ABC\\sim BDA$ ($\\angle B$ wspólny). Stosunek boków:", math: "$\\frac{BD}{AB}=\\frac{AB}{BC}\\Rightarrow BD=\\frac{9}{4}=2{,}25$" }] },',
'      { num: 21, text: "Dany jest trójkąt $ABC$, w którym $|AB|=11$, $|BC|=12$ oraz $|\\angle ABC|=60°$. Oceń prawdziwość poniższych stwierdzeń (P/F): 1. Trójkąt $ABC$ jest równoramienny.  2. Pole trójkąta $ABC$ jest równe $33\\sqrt{3}$.", type: "zamknięte", answer: "F, P", solution: [{ step: "Z tw. cosinusów: $AC^2=133$, $AC\\neq AB$. Trójkąt nie jest równoramienny — F.", math: "" }, { step: "Pole: $P=\\frac{1}{2}\\cdot 11\\cdot 12\\cdot\\sin60°=33\\sqrt{3}$ — P.", math: "" }] },',
'      { num: 22, text: "W kartezjańskim układzie współrzędnych $(x,y)$ dany jest kwadrat $ABCD$, w którym $A=(4,-1)$. Przekątne tego kwadratu przecinają się w punkcie $S=(1,3)$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Przekątna kwadratu $ABCD$ ma długość. A. $5$  B. $7$  C. $10$  D. $14$", type: "zamknięte", answer: "C", solution: [{ step: "Pół-przekątna $|AS|=\\sqrt{9+16}=5$:", math: "$d=2\\cdot 5=10$" }] },',
'      { num: 23, text: "W kartezjańskim układzie współrzędnych $(x,y)$ proste $k$ oraz $l$ są określone równaniami $k\\colon y=(m-2)x+5$ oraz $l\\colon y=-4x+(m+3)$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Proste $k$ oraz $l$ są równoległe, gdy liczba $m$ jest równa. A. $(-4)$  B. $(-2)$  C. $2$  D. $5$", type: "zamknięte", answer: "B", solution: [{ step: "Równoległe gdy równe współczynniki kierunkowe:", math: "$m-2=-4 \\Rightarrow m=-2$" }] },',
'      { num: 24, text: "W kartezjańskim układzie współrzędnych $(x,y)$ punkt $P=(0,0)$ leży na okręgu $\\mathcal{O}$ o środku w punkcie $S=(2,4)$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Okrąg $\\mathcal{O}$ jest określony równaniem. A. $(x-2)^{2}+(y-4)^{2}=2\\sqrt{5}$  B. $(x-2)^{2}+(y-4)^{2}=20$  C. $(x+2)^{2}+(y+4)^{2}=2\\sqrt{5}$  D. $(x+2)^{2}+(y+4)^{2}=20$", type: "zamknięte", answer: "B", solution: [{ step: "Promień:", math: "$r=|SP|=\\sqrt{4+16}=\\sqrt{20}$, więc $r^2=20$" }] },',
'      { num: 25, text: "Tworząca stożka ma długość $8$. Kąt rozwarcia tego stożka ma miarę $120°$. Oblicz objętość tego stożka. Zapisz obliczenia.", type: "otwarte", answer: "$V=64\\pi$", solution: [{ step: "Kąt między tworzącą a osią = $60°$. $r=8\\sin60°=4\\sqrt{3}$, $h=8\\cos60°=4$.", math: "" }, { step: "Objętość:", math: "$V=\\frac{1}{3}\\pi(4\\sqrt{3})^2\\cdot 4=\\frac{1}{3}\\pi\\cdot 48\\cdot 4=64\\pi$" }] },',
'      { num: 26, text: "Objętość sześcianu jest równa $729$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Długość przekątnej tego sześcianu jest równa. A. $9\\sqrt{3}$  B. $9\\sqrt{2}$  C. $3\\sqrt{3}$  D. $3\\sqrt{2}$", type: "zamknięte", answer: "A", solution: [{ step: "Bok: $a=\\sqrt[3]{729}=9$. Przekątna:", math: "$d=a\\sqrt{3}=9\\sqrt{3}$" }] },',
'      { num: 27, text: "Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Wszystkich liczb naturalnych trzycyfrowych nieparzystych, w których zapisie dziesiętnym występuje dokładnie jeden raz cyfra $0$, jest. A. $45$  B. $50$  C. $54$  D. $81$", type: "zamknięte", answer: "A", solution: [{ step: "Postać $\\overline{a0b}$: $a\\in\\{1..9\\}$ (9 możliwości), $b\\in\\{1,3,5,7,9\\}$ (5 możliwości):", math: "$9\\times5=45$" }] },',
'      { num: 28, text: "Doświadczenie losowe polega na dwukrotnym rzucie symetryczną sześcienną kostką do gry (ścianki 1–6 oczek). Zdarzenie $A$: suma wyrzuconych oczek równa $11$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Prawdopodobieństwo zdarzenia $A$ jest równe. A. $\\frac{1}{36}$  B. $\\frac{6}{36}$  C. $\\frac{11}{36}$  D. $\\frac{2}{36}$", type: "zamknięte", answer: "D", solution: [{ step: "Pary dające sumę 11: $(5,6)$ i $(6,5)$ — 2 sprzyjające:", math: "$P(A)=\\frac{2}{36}$" }] },',
'      { num: 29, text: "Średnia arytmetyczna siedmiu liczb: $1, 2, 3, 4, 5, x, y$, jest równa $3$. Dokończ zdanie. Wybierz właściwą odpowiedź spośród podanych. Suma $x+y$ jest równa. A. $4$  B. $5$  C. $6$  D. $7$", type: "zamknięte", answer: "C", solution: [{ step: "Suma 7 liczb = $3\\cdot7=21$. Suma $1+2+3+4+5=15$:", math: "$x+y=6$" }] },',
'      { num: 30, text: "Na diagramie słupkowym przedstawiono wyniki sprawdzianu z matematyki w klasie liczącej $24$ uczniów (oceny 1–6 na osi poziomej, liczba uczniów na osi pionowej). Uzupełnij zdania: 1. Mediana ocen uzyskanych z tego sprawdzianu przez uczniów tej klasy jest równa ...  2. Dominanta ocen uzyskanych z tego sprawdzianu przez uczniów tej klasy jest równa ...", type: "otwarte", answer: "1. Mediana $=4{,}5$; 2. Dominanta $=6$", solution: [{ step: "Wg diagramu (oceny 1–6 = 2,3,4,5,3,7 uczniów). 12. i 13. uczeń: ocena 4 i ocena 5.", math: "Mediana $=4{,}5$" }, { step: "Ocena 6 ma 7 uczniów (najwięcej):", math: "Dominanta $=6$" }] },',
'      { num: 31, text: "Rozważamy wszystkie prostopadłościany $ABCDEFGH$, w których krawędź $BC$ ma długość $4$ oraz suma długości wszystkich krawędzi wychodzących z wierzchołka $B$ jest równa $15$. Niech $P(x)$ oznacza funkcję pola powierzchni całkowitej takiego prostopadłościanu w zależności od długości $x$ krawędzi $AB$. Wyznacz wzór i dziedzinę funkcji $P$. Oblicz długość $x$ krawędzi $AB$ tego z rozważanych prostopadłościanów, którego pole powierzchni całkowitej jest największe. Zapisz obliczenia.", type: "otwarte", answer: "$P(x)=-2x^{2}+22x+88$, $D=(0,11)$, $x=\\frac{11}{2}$", solution: [{ step: "Krawędzie z $B$: $x$, $4$, $h$. Suma: $x+4+h=15\\Rightarrow h=11-x$. Dziedzina: $x\\in(0,11)$.", math: "" }, { step: "Pole całkowite:", math: "$P=2(4x+4(11-x)+x(11-x))=-2x^2+22x+88$" }, { step: "Maksimum paraboli: $x=-\\frac{22}{-4}=\\frac{11}{2}$", math: "" }] }'
)

# Lines are 0-indexed. Tasks are at lines 226 to 256 (0-indexed), i.e., file lines 227-257
$before = $lines[0..225]
$after = $lines[257..($lines.Length - 1)]

$newContent = ($before + $newTasks + $after) -join "`n"
# Preserve Windows line endings from original? Check:
$originalEnding = if ($content.Contains("`r`n")) { "`r`n" } else { "`n" }
# Write with UTF8 no BOM
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
[System.IO.File]::WriteAllText($file, $newContent, $Utf8NoBomEncoding)
Write-Host "Done! Replaced tasks for 2025 exam."
